/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import {AnalysedCatalog, AnalysedComponentApi, AnalysedFunctionApi} from '../../analyzer/types.js';
import {sanitizeIdent, toSnakeCase, typeToPython} from './type-mapper.js';

export const LICENSE_HEADER = `# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
`;

export interface PythonEmitterOptions {
  baseImport?: string;
  catalogName?: string;
}

function extractCatalogName(catalogId: string): string {
  const parts = catalogId.split('/').filter(Boolean);
  let last = parts[parts.length - 1] || 'catalog';
  last = last.replace(/\.json$/, '');
  if (last === 'catalog' && parts.length > 1) {
    const prev = parts[parts.length - 2].replace(/\.json$/, '');
    if (prev) {
      last = prev;
    }
  }
  return last.replace(/[^a-zA-Z0-9_]/g, '_');
}

export class PythonEmitter {
  readonly catalog: AnalysedCatalog;
  readonly baseImport: string;
  readonly catalogName: string;

  constructor(catalog: AnalysedCatalog, options: PythonEmitterOptions = {}) {
    this.catalog = catalog;
    this.baseImport = options.baseImport || 'a2ui.builder.base';
    this.catalogName = options.catalogName || extractCatalogName(catalog.catalogId) || 'catalog';
  }

  /**
   * Generates the entire catalog as a single consolidated Python module string.
   */
  generate(): string {
    const lines: string[] = [
      LICENSE_HEADER.trim(),
      '',
      '# ==============================================================================',
      '# CODE GENERATED BY @a2ui/cli. DO NOT EDIT DIRECTLY.',
      '#',
      `# Catalog ID: ${this.catalog.catalogId}`,
      '#',
      '# This file was automatically generated by the A2UI CLI code generator.',
      '# Any manual modifications will be lost upon regeneration.',
      '# ==============================================================================',
      `"""Type-safe A2UI builders for ${this.catalogName} (version ${this.catalog.specVersion}).`,
      '',
      'AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.',
      'Generated by @a2ui/cli.',
      '"""',
      '',
      '__a2ui_codegen__ = "@a2ui/cli"',
      '',
      'from typing import Any, Mapping, Literal, Optional, Sequence, Union',
      '',
      `from ${this.baseImport} import (`,
      '    Action,',
      '    CheckRule,',
      '    ComponentBuilderNode,',
      '    ComponentRef,',
      '    ComponentTree,',
      '    DataBinding,',
      '    DynamicChildList,',
      '    ExternalComponentBuilderNode,',
      '    FunctionCall,',
      '    IdAllocator,',
      '    Slot,',
      '    SlotList,',
      '    bind,',
      '    create_surface,',
      '    flatten_component_tree,',
      '    update_components,',
      ')',
      '',
      '',
      'def _serialize_prop(val: Any) -> Any:',
      '    if hasattr(val, "to_dict"):',
      '        return val.to_dict()',
      '    if isinstance(val, (list, tuple)):',
      '        return [_serialize_prop(item) for item in val]',
      '    if isinstance(val, dict):',
      '        return {k: _serialize_prop(v) for k, v in val.items()}',
      '    return val',
      '',
      '',
      '# =============================================================================',
      '# Types & Enums',
      '# =============================================================================',
      '',
    ];

    for (const [enumName, enumDesc] of this.catalog.enums.entries()) {
      const vals = enumDesc.values.map(v => `"${v}"`).join(', ');
      lines.push(`${enumName} = Literal[${vals}] | str`);
    }
    lines.push('');
    lines.push('');

    lines.push('# =============================================================================');
    lines.push('# Components');
    lines.push('# =============================================================================');
    lines.push('');

    for (const comp of this.catalog.components.values()) {
      lines.push(this.generateComponentClass(comp));
      lines.push('');
    }

    if (this.catalog.functions.size > 0) {
      lines.push('# =============================================================================');
      lines.push('# Functions');
      lines.push('# =============================================================================');
      lines.push('');
      for (const fn of this.catalog.functions.values()) {
        lines.push(this.generateFunctionDef(fn));
        lines.push('');
      }
    }

    lines.push('# =============================================================================');
    lines.push('# Exports');
    lines.push('# =============================================================================');
    lines.push('');

    const allExports = [
      ...Array.from(this.catalog.enums.keys()),
      ...Array.from(this.catalog.components.keys()),
      ...Array.from(this.catalog.functions.keys()).map(f => toSnakeCase(f)),
      'Action',
      'CheckRule',
      'ComponentBuilderNode',
      'ComponentRef',
      'ComponentTree',
      'DataBinding',
      'DynamicChildList',
      'ExternalComponentBuilderNode',
      'FunctionCall',
      'IdAllocator',
      'Slot',
      'SlotList',
      'bind',
      'create_surface',
      'flatten_component_tree',
      'update_components',
    ].map(e => `"${e}"`);

    lines.push(`__all__ = [${allExports.join(', ')}]`);
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Emits the generated single-file catalog module to disk.
   * If targetPath ends in .py, writes directly to that file.
   * Otherwise, treats targetPath as a directory and writes `<catalogName>.py`.
   */
  emit(targetPath: string): string[] {
    let filePath: string;
    if (targetPath.endsWith('.py')) {
      filePath = targetPath;
      fs.mkdirSync(path.dirname(filePath), {recursive: true});
    } else {
      fs.mkdirSync(targetPath, {recursive: true});
      filePath = path.join(targetPath, `${this.catalogName}.py`);
    }

    fs.writeFileSync(filePath, this.generate(), 'utf-8');
    return [filePath];
  }

  private generateComponentClass(comp: AnalysedComponentApi): string {
    const lines: string[] = [`class ${comp.name}(ComponentBuilderNode):`];

    const doc = comp.description || `${comp.name} component.`;
    lines.push(`    r"""${doc}"""`);
    lines.push('');
    lines.push(`    component: Literal["${comp.name}"] = "${comp.name}"`);

    for (const [pName, prop] of comp.properties.entries()) {
      if (pName === 'component') continue;
      const pyName = sanitizeIdent(pName);
      const pyType = typeToPython(prop.type);

      if (prop.isRequired) {
        lines.push(`    ${pyName}: ${pyType}`);
      } else {
        let defaultStr = 'None';
        if (prop.defaultValue !== undefined) {
          if (typeof prop.defaultValue === 'string') {
            defaultStr = `"${prop.defaultValue}"`;
          } else if (typeof prop.defaultValue === 'boolean') {
            defaultStr = prop.defaultValue ? 'True' : 'False';
          } else if (typeof prop.defaultValue === 'number') {
            defaultStr = String(prop.defaultValue);
          }
        }
        lines.push(`    ${pyName}: Optional[${pyType}] = ${defaultStr}`);
      }
    }

    lines.push('');
    // to_dict
    lines.push('    def to_dict(self) -> dict[str, Any]:');
    lines.push('        d: dict[str, Any] = {"component": self.component}');
    for (const pName of comp.properties.keys()) {
      if (pName === 'component' || pName === 'id') continue;
      const pyName = sanitizeIdent(pName);
      lines.push(`        if self.${pyName} is not None:`);
      lines.push(`            d["${pName}"] = _serialize_prop(self.${pyName})`);
    }
    lines.push('        if self.id is not None:');
    lines.push('            d["id"] = self.id');
    lines.push('        return d');

    return lines.join('\n');
  }

  private generateFunctionDef(fn: AnalysedFunctionApi): string {
    const paramSigs: string[] = ['*'];
    const argsDictItems: string[] = [];
    const pyFnName = toSnakeCase(fn.name);

    for (const [pName, pDesc] of fn.parameters.entries()) {
      const pyParam = sanitizeIdent(pName);
      const pyType = typeToPython(pDesc.type);
      if (pDesc.isRequired) {
        paramSigs.push(`${pyParam}: ${pyType}`);
      } else {
        paramSigs.push(`${pyParam}: Optional[${pyType}] = None`);
      }
      argsDictItems.push(
        `    if ${pyParam} is not None:\n        args["${pName}"] = ${pyParam}.to_dict() if hasattr(${pyParam}, "to_dict") else ${pyParam}`,
      );
    }

    paramSigs.push('call_id: Optional[str] = None');
    const paramsStr = paramSigs.join(', ');

    const doc = fn.description || `Invokes catalog function ${fn.name}.`;
    const lines: string[] = [
      `def ${pyFnName}(${paramsStr}) -> FunctionCall:`,
      `    r"""${doc}"""`,
      '    args: dict[str, Any] = {}',
    ];
    if (argsDictItems.length > 0) {
      lines.push(argsDictItems.join('\n'));
    }
    lines.push(`    return FunctionCall(call="${fn.name}", args=args, call_id=call_id)`);

    return lines.join('\n');
  }
}
